name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  intl: ^0.18.1
  image_picker: ^1.1.0
  firebase_storage: ^12.4.10
  lottie: ^3.1.2
  qr_flutter: ^4.0.0  
  http: ^1.1.0
  cloudinary_public: ^0.23.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/animations/success.json
  uses-material-design: true

